### ISSUE TITLE
Add emath because its col libary

### ISSUE THREAD

**Issue by suprohub** [tversteeg/chuot#105]

**Comment by tversteeg** [comment]
This looks to be specific to GUIs? Also, you can directly pass `emath::Pos2` or any of the other types, also from other libraries like `glam`, to all functions accepting a tuple, because they implement [`impl From<Pos2> for (f32, f32)`](https://docs.rs/emath/latest/src/emath/pos2.rs.html#79):

```rust
let vec = emath::Vec2::new();

ctx.sprite(..).translate(vec);
```

**Comment by suprohub** [comment]
Ok

**Comment by suprohub** [comment]
But why we use tuples instead of structs?

**Comment by tversteeg** [comment]
Because all the math libraries implement `From<Type> for (f32, ..)` which allows us to interface with all of them. Another option is to use static arrays `[f32; 2]`, but I prefer tuples.

**Comment by suprohub** [comment]
> Because all the math libraries implement `From<Type> for (f32, ..)` which allows us to interface with all of them. Another option is to use static arrays `[f32; 2]`, but I prefer tuples.
> 
> If you want to talk about the design decisions, it's better to chat on [Matrix](https://matrix.to/#/#chuot-general:one.ems.host).

Matrix responce ERR_TIMED_OUT (provider block)

**Comment by suprohub** [comment]
but emath implements into<(f32, ..)>

**Comment by tversteeg** [comment]
Exactly! So you can use it in your game, without it having to be a dependency of Chuột.

**Comment by tversteeg** [comment]
I've changed the Matrix room to matrix.org, is it working for you now? https://matrix.to/#/#chuot:matrix.org

**Comment by suprohub** [comment]
no

**Comment by suprohub** [comment]
i think matrix blocks me
