### ISSUE TITLE
Object (entity)

### ISSUE THREAD

**Issue by suprohub** [tversteeg/chuot#113]
i want to add objects, see example
```
impl Game for GameState {
    // ...
   fn init(&mut self, ctx: Context) {
       ctx.objects.push(SimpleObject::default())
   }
}

impl Object for SimpleObject {
    fn update()
    fn render()
    fn init()
    //...
    // methods call automatically
}
```

**Comment by tversteeg** [comment]
I think putting this in the engine is not optimal, since the internal structure must be `Vec<Box<dyn Object>>`.
Also, with the current usage this promotes not batching draw operations, for example.
