### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by suprohub** [tversteeg/chuot#84]
there the camera?

**Comment by tversteeg** [comment]
At the moment, you'll have to do it manually. I have been considering adding it, but I'm not sure what a nice user-friendly API would be for that.

Some things to consider:

- Is the state of the camera part of the library, or is it the user's responsibility?
- When drawing a sprite, is using a camera opt-in or opt-out?
- Should the camera handle depth effects, like parallax scrolling?

Any suggestions?

**Comment by suprohub** [comment]
1 part of the library
2 I didnt quite understad the question even through a translator
3 yes

**Comment by tversteeg** [comment]
> 2 I didnt quite understad the question even through a translator

Should all sprite elements be automatically drawn with the camera or not? And how do you choose to draw something with the camera or not?

Also, is there only one camera or can there also be multiple ones?
