### ISSUE TITLE
Agpl license

### ISSUE THREAD

**Issue by jonatino** [tversteeg/chuot#91]
Just found this engine and I love it so far. Very nice work!

I must ask, why the AGPL license? If I’m not mistaken, wouldn’t this require games that are written using your engine be open source and distribute the source code?

Would you consider switching to an MIT license?

**Comment by tversteeg** [comment]
Thank you!

You are correct, using this game engine to make games requires you to disclose the game's source code.

I've made the deliberate choice to make the license AGPL to benefit the FOSS gamedev community. I should probably write something more extensive about the license choice on the website or in the README.

Either way, I would not consider switching to an MIT license.

https://drewdevault.com/2024/04/19/2024-04-19-Copyleft-is-not-restrictive.html

**Comment by jonatino** [comment]
I respect that decision. Good luck with the project!
