### ISSUE TITLE
shaders for sprites

### ISSUE THREAD

**Issue by suprohub** [tversteeg/chuot#92]
how add shaders to sprites? or change color?

**Comment by tversteeg** [comment]
At the moment, you can't. I'm okay with opening up the shader pipeline for custom shaders though. Not sure how to prioritize this over other feature requests, but of course any PRs are welcome!

**Comment by tversteeg** [comment]
Added some very basic support for it in 27627f2, but I feel it's still missing a lot of features that make it actually useful, like binding values and other textures…
